### PR TITLE
Use markdown links in readme

### PR DESCRIPTION
**Pull request by IanVS**
This converts the badge links at the top of the readme to markdown links, which do not clutter up the file as much.  Also, my editor (Atom) was not syntax highlighting correctly before this change.

It also removes some trailing spaces and converts tab indentaions to two-spaces.

### CODE REVIEW

**Comment by gilbarbara** [comment]
I like the links to open in a new tab by default which markdown cannot do, so I would like to keep that way..
Thanks

**Comment by IanVS** [comment]
That's understandable, but FYI your links are currently _not_ opening in a new window in my browser.

**Comment by gilbarbara** [comment]
yeah, I just saw that.. Probably github changed something in their markdown parser. I'll look into it.
👍

**Comment by gilbarbara** [comment]
I ended up removing the html links from the README but I don't like using variables in markdown.
Thanks anyway!

**Comment by IanVS** [comment]
:+1: works for me!

**Pull request closed without merging**
