### PR TITLE
Issue 478: move `if` statement inside setTimeout to prevent type errors

### PR DESCRIPTION
**Pull request by thebesson**
A solution for a bug described in this issue: https://github.com/gilbarbara/react-joyride/issues/478

### CODE REVIEW

**Comment by thebesson** [comment]
Hi, @gilbarbara, is it normal for "bundlesize" to run for so long?

**Comment by gilbarbara** [comment]
@thebesson no, it should finish at the same time as travis. However it is buggy and doesn't run properly with PRs

**Comment by thebesson** [comment]
@gilbarbara thanks! is there a way to restart the process? Doesn't look like this one is going to finish

**Comment by thebesson** [comment]
Thanks for the merge, @gilbarbara! We have a feature that we want to release that is currently blocked by this bug and hence I was wondering when this would be released? Is there anything I can do to help/expedite it if necessary? Thanks again!

**Comment by gilbarbara** [comment]
Added in 2.0.4.
Thanks

**Pull request merged**
