### PR TITLE
Improvements on accessibility

### PR DESCRIPTION
**Pull request by sbrigham**
This change removes the "keyboardNavigation" prop. It makes keyboard navigation always a thing. The change locks your tab focus inside a Tooltip when it gets opened. Keyboard navigation will now be just tabbing through all of the next, skip, close buttons and hitting enter on the keyboard. The user will still be able to hit escape to close the Tooltip.

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hey,

You should have open an issue before submitting a PR since this would break the basic functionality.

Sometimes you don't want the user to close the tooltip with ESC, this won't change and has nothing to do with accessibility.

Adding a `tabIndex` to improve accessibility it's a good thing and you can open a new PR adding just that if you want. But please don't add new dependencies...

**Comment by sbrigham** [comment]
@gilbarbara Sounds good. Thanks for the quick response.

**Comment by gilbarbara** [comment]
Looking at the PR code, it feels way too complicated.

If you just need to add tabIndex and aria-labels it should be done directly in the Tooltip component without recomposition or any other dependency. A simple `++idx` would do the trick, isn't?

**Comment by sbrigham** [comment]
The issue is with locking the focus though. You need to keep track of tabs so the user is locked in the tooltip. This is mentioned in https://github.com/gilbarbara/react-joyride/issues/101

**Comment by gilbarbara** [comment]
Humm, okay. Always mention the issue you are trying to fix in your PRs to avoid confusion.

So I think this should be split into multiple PRs.
"Improvements on accessibility" is a very specific task and locking the focus is not related to it.

Btw, how do you propose to "lock" the keyboard navigation?

**Comment by gilbarbara** [comment]
I'm moving the discussion to the original issue, just to keep things organized.

**Pull request closed without merging**
