### PR TITLE
Custom scroll containers specified per step

### PR DESCRIPTION
**Pull request by xveganxxxedgex**
This change includes the ability to specify the container you want to scroll per each step via the scrollContainerSelector prop.

For non-continuous tours, or if a step is closed and the beacon shows in a child scrollable container, the beacon will only show if the target element is in view. Scrolling to the next step will happen automatically, but this prevents against having weird behaviour if the user closes a step, scrolls the scroll container, then tries to continue while the target is out of view.

There is a known downfall that I haven't quite found a solution for, related to the tooltip needing to readjust after a delay. It’s stuck in an awkward event cycle, IIUC something like below:

- State is updated to go to the next step, which causes a render and a calculate position call, which then updates the state with the new position
- Tooltip renders and binds to the initial position
- We need to scroll both the child scrollable container, and the body in case both are out of view
- Position is calculated after both scrolling events are complete
- Rerender is triggered for tooltip using the correct position after scrolling

So essentially, what will happen when using specified scrollable containers is the tooltip will appear, but may be bound to an incorrect position or the point of the tooltip won't be centered or correctly placed over the target. After scrolling completes, it should update to the correct position, but it is noticeable since there's a delay. If anyone knows of a way around this or has any suggestions, I'd be happy to implement the solution, I just couldn't find a good way around it myself yet.

~~Unrelated to this feature, but this PR also includes a change to the callback functionality. Close and skip callbacks were using 'next' as the callback action, instead of using the 'close' or 'skip' as the action. So if the action is either 'close' or 'skip', it will use those values as the action, otherwise will use the previous action.~~ Removed this since this was part of a recent release

Thanks!

### CODE REVIEW

**Comment by gilbarbara** [comment]
wow, that's a lot of code. I'll try to run the demo and understand most of it.

**Comment by IanVS** [comment]
@chriscain has worked on solving this same problem as well, and may have
some insights on challenges and corner cases.

**Comment by xveganxxxedgex** [comment]
It seems my code keeps causing failed tests, but I haven't been able to run the tests locally due to a connection error. Is there a way I can resolve that so I can see what's up with that test? Thanks!

**Comment by gilbarbara** [comment]
The tests can't run locally because Sauce Connect needs to create a tunnel with a secret key.

**Comment by IanVS** [comment]
First of all, @xveganxxxedgex, thanks for all the hard work on this!  It's a real problem that we would like to solve, and you've made some good progress here.

Unfortunately, though, I think we need to take a step back and try to find another approach.  You've made a lot of changes to the code, and we're worried that not all of it is necessary.  And in the end, as you've noted in your PR description, there are still some shortcomings.  It's not going to be a great end-user experience if the tooltip appears, elements scroll, and then the tooltip re-adjusts.

I think at a high-level, the strategy that react-joyride should follow in this case is to:

1) Scroll the scroll-container into the viewport if necessary
2) Scroll the targeted element within the scroll-container into the viewport
3) _Then_ show the tooltip
4) (ideally) Hide the tooltip if the target element scrolls outside of the visible portion of the scroll-container.

I don't have any magic-bullet solutions for how to accomplish this.  We don't think you need to use callbacks, and instead you should be able to use React component lifecycle hooks like `componentDidUpdate` to determine when scrolling is finished.  I'm sorry I don't have more to give you right now in the way of direct feedback, but as this PR stands, we can't merge it.  If you're still interested in working on this, I'd suggest taking what you've learned so far, starting from a fresh branch off of `master`, and seeing if you can implement the four steps above without callbacks and with less code overall.  Feel free to discuss your strategy here before jumping straight into code, and we will give as much guidance as we can.

Again, thanks for the hard work here, we really appreciate it.

**Comment by xveganxxxedgex** [comment]
Thanks for your review and feedback, @IanVS. Apologies it wasn't an ideal solution, but I agree that there were definitely downfalls and improvements that could be made. I'll try to think more on alternative methods if I can get some more down time.

Thanks again!

**Pull request closed without merging**
