### PR TITLE
Scrollable child elements

### PR DESCRIPTION
**Pull request by xveganxxxedgex**
This is a rewrite of the feature requested from [PR#174](https://github.com/gilbarbara/react-joyride/pull/174).

Using the feedback from the PR, this feature now calculates child scrolling element before rendering, which prevented the use of callbacks and other messy workarounds.

When the joyride tries to calculate the position, it checks if this element has a parent scroll element specified. If it does, it will scroll that element to the target position, then will call calcPlacement again to calculate the body to find the target now that it should be in view.

This also does have logic to bind the beacon to the element in the event that the parent scroll container is scrolled. 

I hope this PR is a bit better than the previous one, and I'd also be very grateful for any feedback or suggestions you may have. 

Let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by xveganxxxedgex** [comment]
Argh, through more testing and trying to use this in my other project real-life instance, it seems it's still not perfect. I'll continue trying to debug and fix, but there may be something obvious I'm missing, so I figured it was worth documenting in case others have any thoughts/suggestions.

The current found issues are:

- Tooltip window is not defaulting to the correct position and can cut off/overlap the target element. 
- Tooltip arrow is slightly off-centered sometimes. 
- Sometimes when closing the tooltip, the beacon will not appear even though target is in view.

As a side note, I also pushed up a change to allow setting an option to hide the close buttons on the tooltip.

**Comment by dekkofilms** [comment]
Are there any updates on this? I would love to have a feature like this in our current app, and didn't know what the status is.

**Comment by xveganxxxedgex** [comment]
@dekkofilms Unfortunately, I don't have an update. The last time I looked at this branch, I wasn't able to figure out how to get the tests to pass, but not sure if that's what's holding this PR up. I've just been using my fork with this feature in the meantime.

**Comment by gilbarbara** [comment]
This will be handled differently in V2.
Thanks for the PR

**Pull request closed without merging**
