### PR TITLE
Allow pointer-events in overlay hole

### LINKED ISSUE #148: Make hole a "real" hole in the overlay
My use case involves prompting the user to take some action within my app, like clicking a button in order to move to the next step of the tour.  Because of that, I need to allow hover states and click handling to pass through the hole in the overlay, but be blocked everywhere else.  I have a working prototype and would be willing to submit a PR if you're agreeable to the idea, @gilbarbara.

### PR DESCRIPTION
**Pull request by IanVS**
Fixes #148.

## Description

This allows the user to interact with the app under the overlay within the "hole", when using a mouse.  This means that hover states will be shown through the hole, and click events will be passed through the overlay to underlying DOM elements.  

It updates the demo, in order to show the functionality.  Here is a short gif of it in action:

click-in-hole

This also does a little bit of refactoring to move some significant calculations out of the render loop, instead performing them on initial mount and subsequent prop changes, storing the results in component state.  This may have some side-benefits of increased performance.

## Limitations
This will not work properly on touch screens for the time being, since it relies on `mousemove` events.  A subsequent effort can address this deficiency if needed.

Also, I haven't found a way to run the tests locally, so I have a feeling that CI will fail.  I may need a few tries to get the tests passing, we'll see.

### CODE REVIEW

**Comment by IanVS** [comment]
OK, @gilbarbara tests are passing.  Let me know what you think.

**Comment by gilbarbara** [comment]
@IanVS 
We need to improve this to allow touchscreen to function.
Maybe set a `touchstart` listener?

**Comment by IanVS** [comment]
To be honest I'm not very familiar with the touch APIs, but I agree we
should fix that. I'll open a new issue for it.

**Comment by IanVS** [comment]
https://github.com/gilbarbara/react-joyride/issues/178 opened.

**Pull request merged**
