### PR TITLE
Add capability to handle multiple spotlights

### PR DESCRIPTION
**Pull request by pswai**
This PR add capability to display multiple spotlights during the tour. It allows `target` to be a selector that selects multiple elements and cast spotlights to all of them.

Notable stuffs:
- This does not create multiple tooltip, only one tooltip will be created (existing behaviour)
- This does not affect the positioning of tooltip, the tooltip will always be position to the first element (existing behaviour)
- This PR does not handle `NodeList` as target. It handles only the selector-string case.

Related issues: #389

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hello,

Which problems would it solve?
Having multiple spotlights for a single step feels like bad UX. The idea of this package is to have a "guided" tour. A step with multiple spotlights feels wrong and cognitively complex.

**Comment by luluuu** [comment]
Hi @gilbarbara,
I need this feature too, I understand what you are saying, that the idea of this package is to have a "guided" tour. But, usually, developers will implement your package after building an app, so the html architecture will be already defined, and implemented. Having multiple spotlight option will allow us for example to highlight two following or "brother" elements without modify the html, sometimes just adding a wrapper will break things. It is true that in most cases it feels wrong but I think you should let your package users decide if it is wrong or not :)

**Comment by gilbarbara** [comment]
@luluuu 

> And thank you by the way, your package is really great.

Thanks!

> Having multiple spotlight option will allow us for example to highlight two following or "brother" elements without modify the html, sometimes just adding a wrapper will break things. It is true that in most cases it feels wrong but I think you should let your package users decide if it is wrong or not :)

This library doesn't add wrappers or anything and having multiple spotlights wouldn't change that, so, I'm a little lost about what you are talking about.

**Comment by pswai** [comment]
@gilbarbara Sorry for the late reply, yesterday was really packed for me.

This PR solves two major problems:
1. **Collection step** - As @luluuu pointed out, having multiple spotlights is useful when we need to cast spotlight on a collection of elements in a single step. I will elaborate more on this.
2. **Product delivery problem** - This is ironic, but more often than not the UX is not decided by us engineers but the UX designers, PM or even the CEO.

Let's talk about several use cases for multiple spotlights.

### Navigation Sidebar
_(@luluuu and my case)_
Navigation Sidebar is often implemented with unordered list. Let's say there is this sidebar:
```html
<ul>
  <li>Home</li>
  <li>Free Feature 1</li>
  <li>Free Feature 2</li>
  <li>Premium Feature 1</li>
  <li>Premium Feature 2</li>
  <li>Settings</li>
</ul>
```
A sensible tour to this sidebar for a free-tier user is probably:
1. The entire Sidebar - Tell user this is for navigation
1. Introduction to Home
1. Introduction to Free Feature 1
1. Introduction to Free Feature 2
1. Introduction to Premium Feature 1, ask user to upgrade
1. Introduction to Premium Feature 2, ask user to upgrade
1. Introduction to Settings

If we think about it, having 2 steps to introduce the Premium Features to a free-tier user is not very good, why not combining these 2 steps into 1, saying "These are premium features you can access by upgrading!".

One might argue that the Premium Features should not appear in the Sidebar. This can be a long debate and really up to the decisions of each businesses. So let's focus on how we as developer can do that.

The way to do it with a single spotlight is as @luluuu has described, we need to wrap the 2 `<li>` into a single element. So here the markup will need to be changed to:

```html
<ul>
  <li>Home</li>
  <li>Free Feature 1</li>
  <li>Free Feature 2</li>
  <li>
    <div>Premium Feature 1</div>
    <div>Premium Feature 2</div>
  </li>
  <li>Settings</li>
</ul>
```
That needs special styling, we can improve it slightly by only wrapping it during tour. But there is a huge architectural flaw now: The Sidebar component needs to be aware of the tour now. 

The situation worsen when the Premium Features are not side-by-side. The wrapper technique won't work.

With multiple spotlights, the scenarios above can be achieved easily.

### Table Column
Imagine an account transaction table in online banking. We want to give a tour to the table, explaining the functionality of each columns. (Date, Description, Debit, Credit)

Table in HTML is row-based. On top of that, non-table elements (e.g. `div`) do not work in all table-elements except `th` and `td`. So selecting a column as a single element is technically impossible.

With multiple spotlights, we can do `target: ".transaction-table .credit-cell"` to select all cells in the "Credit" column, then specify 0 `spotlightPadding` to make it appears like the entire column is selected.

The way to do this with single spotlight will be highlighting only the `th`, which I think is not as good UX as highlighting the entire column. Again, this is subjective and most of the time we are not the one to make the decision.

### Toolbox
Imagine the sidebar toolbox of photoshop/gimp (like below). We want to give a tour to the functionalities.
image

Having a tour for every single button is definitely a no-deal as we can expect 95% of our users cannot stand a 38-steps tour. A better tour would have each step talking about a group of functionalities. So there are "simple selection", "special selection", "dimension manipulation", "colour effects", etc.

So we encounter the problem in the screenshot above: "special selection" tools are in two different rows. Multiple spotlights help implementing this easily.

With single spotlight, we either need to change the layout of the toolbox, or change the way to do the tour.

### Potential Drawbacks
To be fair, I need to list down some drawbacks too.

* Multiple spotlights by accident (i.e. user only wanted single spotlight)
* Potential performance issue when there are really lots of spotlights?
* More requests related with multiple spotlights will come in. People might request multiple tooltips, etc.
* I am new to this codebase so i'm not sure what will happen (e.g. scrolling) when there is a spotlight that is out of viewport.

### My Thoughts
I think the enforcement of a good UX is not the responsibility of a library like `react-joyride`. It is the responsibility of the person/team who decides on how to use it. Moreover, the perception of a UX is not determined by hard rules. It is a combination of various factors like culture, target audience and design intention. Try comparing Japanese websites and western websites, even from the same company. ([Here's a good article about it](https://www.infocubic.co.jp/en/blog/website-design/how-japanese-website-design-differs-from-the-west/))

Lastly, it is unfortunate that most of us don't have the authority to make this decision. So having multiple spotlights can potentially save the pay-check of anyone of us (ok this is exaggerating 😅 ). 

Thanks for reading this very long post!

**Comment by luluuu** [comment]
@pswai Thanks for your example ! That's exactly what I meant

**Comment by gilbarbara** [comment]
@pswai 
Ok, good points, I'll look into it when I have some time.

But I do not agree that libraries shouldn't enforce good practices.
This is an opinionated library and I'll never take into consideration corporate/marketing bullshit in my open-source work.

**Comment by pswai** [comment]
@gilbarbara Thanks for taking a look at this. If you need assistance on this don't hesitate to contact me :)

Let's don't continue on the unrelated issues anymore, I am sorry if it upsets you.

**Comment by sueyee** [comment]
Hi, I also need a spotlight to handle a target that has a overlapping chart. The spotlight only includes the target. The chart overlapping over the target using css z-index.  Is there a way to have the spotlight include the chart and target in one step?

**Comment by gu-hmlet** [comment]
@gilbarbara Can you take time to follow it?

I think the proposal for this PR is good, our team facing the same problem

**Comment by thanhlmm** [comment]
@gilbarbara Can you take time to follow it?

I think the proposal for this PR is good, our team facing the same problem

**Comment by giorgosavgeris** [comment]
👍  We are facing the same issue. It would be great to have that.

**Comment by gilbarbara** [comment]
@thanhlmm I think would introduce some bugs and it needs more testing, but I don't have time to look into this right now...

**Comment by thanhlmm** [comment]
> @thanhlmm I think would introduce some bugs and it needs more testing, but I don't have time to look into this right now...

Hi, can you list out which aspect you concern. I can support you to check it
Since I already used it in my project and everything ok, so I think it will be fine 💪

**Comment by GiancarlosIO** [comment]
👀

**Comment by EderOBarreto** [comment]
@gilbarbara Is there a reason why this feature doesn't was added yet? I am looking forward to use this feature haha

**Comment by EderOBarreto** [comment]
@gilbarbara Can I help with the tests? I would like to have access to this feature.

**Pull request closed without merging**
