### PR TITLE
fix spotlight twice touch on touch devices

### PR DESCRIPTION
**Pull request by rsnzh**
1.remove css pointer-events and mousemove event
2.add click method on spotlight component if set spotlightClicks true then trigger target element click event

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hey @rsnzh 

You are changing the code style of the updated files, that's not acceptable.

**Comment by gilbarbara** [comment]
Hey @rsnzh 
CI is still failing.

Anyway, I couldn't replicate the behavior you mentioned.
Load this URL: https://nwdc5n.csb.app/controlled, and when you click the menu through the spotlight, it is only called once.

Also, I'm against imperative actions, such as `element.click()`. This can lead to other problems...

**Comment by gilbarbara** [comment]
Also, if you check the Modal [demo](https://nwdc5n.csb.app/modal), the spotlight click allows the input to be selected, so it's not triggering a click in the element.

**Comment by rsnzh** [comment]
> Hey @rsnzh CI is still failing.
> 
> Anyway, I couldn't replicate the behavior you mentioned. Load this URL: https://nwdc5n.csb.app/controlled, and when you click the menu through the spotlight, it is only called once.
> 
> Also, I'm against imperative actions, such as `element.click()`. This can lead to other problems...

You can reproduce twice clicks on touch devices, just as issues #855 #861 .
`element.click()` might not be the best, but is what I currently think of .

> Also, if you check the Modal [demo](https://nwdc5n.csb.app/modal), the spotlight click allows the input to be selected, so it's not triggering a click in the element.

The result is not the same on touch devices and pc browsers.
maybe add the `spotlightFocus` props, if set true trigger `element.focus()`

**Comment by gilbarbara** [comment]
> You can reproduce twice clicks on touch devices, just as issues #855 #861 .

Yeah, I tested in Chrome and Safari on an iPhone. I closed these issues since I can't replicate them.
Can you try it again?

**Comment by rsnzh** [comment]
> Yeah, I tested in Chrome and Safari on an iPhone. I closed these issues since I can't replicate them. Can you try it again?

I try it on Android Edge and Chrome Desktop and not working expected.

**Comment by gilbarbara** [comment]
The solution doesn't cover all cases. The `target` isn't necessarily the element the user wants to be triggered and imperative calls to the `click` method could throw an error.

**Pull request closed without merging**
