### PR TITLE
Force redrawing step even if the selector is unchanged

### PR DESCRIPTION
**Pull request by nathanstitt**
I've discovered that joyride failed to advance to the next step when it has the same selector as the previous one.  I think this is the issue that's reported in #113 

Note that I added `cherrio` to the package.json, but that's kinda a freebie since `enzyme` already includes it.  It needed to be added because eslint was complaining otherwise.

Happy to rework if there's any suggestions

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hello,

I'm a bit against this approach since you can use a better qualifier for the selector instead of "hacking" its way. Why not use `a:nth-child(2)` or something similar?

Also, you don't need cheerio to get the html, enzyme has a method for that....

**Comment by nathanstitt** [comment]
@gilbarbara thanks for taking a look at the PR, I'm not sure what you mean by "hacking it's way".  The issue I'm attempting to fix is that when consecutive steps have the same identifier, the second step isn't repositioned, which causes it to be set to the default position of `-1000px`.

As noted in https://github.com/gilbarbara/react-joyride/issues/113#issuecomment-270406721 there is a workaround to set the second step to a different selector that points to the same element but in a different way, but that doesn't work for our use case at all.

We're attempting to use react-joyride in a large SPA which fairly dynamic, meaning that often joyride targets will not be available.  We're dynamically deciding to play a tour depending on the availability of steps and other domain specific logic.  There's multiple developers working on the app, and we really want to avoid using brittle selector logic like `a:nth-child(2)`   To avoid things like that and so we can observe step appearance/disappearance, we're using custom wrappers for the steps to point to, with each having a `data-tour-step` attribute for joyride to point at. 

I'm aware that enzyme (we use it also, it's excellent btw :) return's a cheerio wrapper, but in my testing the returned wrapper didn't return a value for `css`.  I'll take another look at it though, I probably did something wrong there.

**Comment by nathanstitt** [comment]
@gilbarbara - I figured out why the cheerio wrapper returned by `render()` was returning null for `css('top')`.  It appears that wrapper is for a wrapper node and what  you really need to query are it's `children()`

Just pushed an update that uses that and removes `cheerio` from the package.

**Comment by gilbarbara** [comment]
About your comment regarding unmounted steps, why don't you stop the tour, update your UI and start it again?

**Comment by nathanstitt** [comment]
Hey @gilbarbara.  In our case we don't want to even start the tour if certain steps are missing. 

I think perhaps you're misunderstanding the severity of bug that I'm attempting to fix.  In this case React Joyride completely fails to display the next step (because it's positioned at -1000px), but does leave the overlay in place.  Since we've also set `disableOverlay: false` the interface is completely covered by the overlay mask and all the user can do is reload the browser.

Given the existence of #113, we're not the only users who've hit this.  It sure seems to me like something that should be fixed, if for no other reason than it'll stop users from filing tickets 😁 

With that said, it's quite likely my fix is non-optimal and it should be done differently.  I'm happy to rework however you think best.

**Comment by nathanstitt** [comment]
Sorry, thought that'd be better - I've removed that commit

**Comment by nathanstitt** [comment]
To further expand on that, I prefer **simple** relative imports because it allows client code to directly import the JSX files.  That can be advantages if they're already using webpack with babel and want to be able use tree shaking.  It's no biggy though, using the compiled source is fine, especially for a relative small codebase like ReactJoyride.

Thanks!

**Pull request closed without merging**
