### PR TITLE
Fix Chrome 61 autoscroll

### PR DESCRIPTION
**Pull request by fsmaia**
Fix issue #268.

### CODE REVIEW

**Comment by jtrevag** [comment]
Looking forward to this fix... but what's up with the build errors @fsmaia?

**Comment by fsmaia** [comment]
I'm checking. Seems like npm run build:demo is failing due to some dependency resolution failure:
```
ERROR in ./src/App.jsx
Module not found: Error: Can't resolve 'file' in '/home/fernando-maia/playground/react-joyride/demo/'
 @ ./src/App.jsx 3:3206-3241
 @ ./index.jsx
Child html-webpack-plugin for "index.html":
       [0] ../~/lodash/lodash.js 540 kB {0} [built]
       [1] ../~/html-webpack-plugin/lib/loader.js!./assets/index.ejs 8.3 kB {0} [built]
       [2] ../~/webpack/buildin/global.js 509 bytes {0} [built]
       [3] ../~/webpack/buildin/module.js 517 bytes {0} [built]

    ERROR in ../~/html-webpack-plugin/lib/loader.js!./assets/index.ejs
    Module not found: Error: Can't resolve 'file' in '/home/fernando-maia/playground/react-joyride/demo/'
     @ ../~/html-webpack-plugin/lib/loader.js!./assets/index.ejs 23:1-35

    ERROR in ../~/html-webpack-plugin/lib/loader.js!./assets/index.ejs
    Module not found: Error: Can't resolve 'file' in '/home/fernando-maia/playground/react-joyride/demo/'
     @ ../~/html-webpack-plugin/lib/loader.js!./assets/index.ejs 25:1-31
```

**Comment by fsmaia** [comment]
Problem fixed. `file-loader` was missing in project dependencies.

**Comment by jtrevag** [comment]
@gilbarbara Any updates on when this can be put into master?

**Comment by olegberman** [comment]
When this will be merged?

**Comment by fsmaia** [comment]
In the meanwhile you can change you package.json dependency to:
```
"react-joyride": "fsmaia/react-joyride",
```

**Comment by fsmaia** [comment]
Due to precommit hook I was fortunately forced to fix lint issues. Instead of changing code style I was actually fixing code style consistence issues in project given rules.

**Comment by gilbarbara** [comment]
@fsmaia This was probably due to an updated version of `eslint-config-airbnb`.
Sometimes they change rules in patch versions. ¯\_(ツ)_/¯

**Pull request merged**
