### PR TITLE
Feature/fix calculating positions

### PR DESCRIPTION
**Pull request by msalsas**
[https://github.com/gilbarbara/react-joyride/issues/124](https://github.com/gilbarbara/react-joyride/issues/124)

Not sure if working for everyone.

### CODE REVIEW

**Comment by gilbarbara** [comment]
@msalsas 
Since your fork is outdated, can you please check this [PR](https://github.com/gilbarbara/react-joyride/pull/215) and let me know if it works for you?

**Comment by msalsas** [comment]
@gilbarbara No, it doesn't. There are no error in the console, but the tutorial is not showing.

**Comment by gilbarbara** [comment]
Tutorial?
Did you look at the code? is it similar to yours? What is missing?

[s]

**Comment by msalsas** [comment]
@gilbarbara Sorry, I mean tour. The code is based on my fork (or similar), but adding the parent element offset to `getBoundingClientRect` (`getBoundingClientRectFromElement` in my fork). Also I had to replace `const winWidth = window.innerWidth;` with `const winWidth = document.body.clientWidth;` in Joyride.jsx.

**Comment by gilbarbara** [comment]
This will be handled by popper.js in V2.
Thanks for the PR

**Pull request closed without merging**
