### PR TITLE
React 18 support

### PR DESCRIPTION
**Pull request by kyh**

### CODE REVIEW

**Comment by mapapuche** [comment]
i need to be support on react 18 too ...

**Comment by kamte** [comment]
@gilbarbara do you have an ETA for this?

**Comment by JoaoJesus94** [comment]
@gilbarbara Any new on this?

**Comment by gilbarbara** [comment]
hey @kyh 

Thanks for the PR but it wasn't that simple to support React 18.
The StrictMode changed significantly and I had to update react-floater and this library Portal to handle the `mount -> unmount -> mount` behavior. 

Anyway, this is superseded by #809

**Pull request closed without merging**
