### PR TITLE
 Tooltip and Beacon component customizable

### PR DESCRIPTION
**Pull request by tobilen**
adresses #299

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hey, I'm not accepting PRs right now as I'm refactoring the code

**Comment by tobilen** [comment]
Hey @gilbarbara,

thanks for the quick response. Any idea on when you might accept PR's again?

In the meantime, i have published the (modified) version of react-joyride in our namespace (@invisionag/react-joyride) for anyone who is interested in this feature. I've kept your copyright info of course.

**Comment by gilbarbara** [comment]
What do you mean by "our namespace"? Published where?

**Comment by tobilen** [comment]
The place i work at. Published on npm under our namespace: https://www.npmjs.com/package/@invisionag/react-joyride

**Comment by gilbarbara** [comment]
😔

**Pull request closed without merging**
