### PR TITLE
Add support for different scrolling containers #61

### PR DESCRIPTION
**Pull request by JohnMBarry**
#61

### CODE REVIEW

**Comment by xveganxxxedgex** [comment]
I needed a similar feature for our project, so I made some adjustments to this forked repo that should be up to date with master and resolve these conflicts. My version also supports the ability to specify parent scroll containers per each step. I'd be happy to submit my PR to either the Cellarise fork, or to the gilbarbara's main repo if that'd help get this feature merged? 

Here's the diff comparison from the main react-joyride repo:
https://github.com/gilbarbara/react-joyride/compare/master...xveganxxxedgex:master

**Comment by gilbarbara** [comment]
@xveganxxxedgex do you have an example?
[s]

**Comment by xveganxxxedgex** [comment]
@gilbarbara I do not atm, embarrassingly, I couldn't figure out how to get a local env working. If I can get that example working, I can try to add one in there. Is there something I'm missing to get it to bundle for that example page?

**Comment by xveganxxxedgex** [comment]
@gilbarbara Apologies for the delay, finally figured out how to get the test environments working. This example shows the scrollable elements specified at the step level (step #6):

https://xveganxxxedgex.github.io/react-joyride/

**Comment by gilbarbara** [comment]
@xveganxxxedgex The extra scrollable step doesn't show the beacon, did you get this too?

**Comment by xveganxxxedgex** [comment]
@gilbarbara How were you trying to show the beacon? If I go through the steps, then x out of the fifth step, my page will scroll and I see the beacon:

screen shot 2016-12-07 at 3 48 22 pm

I did push up a change earlier today, but the demo may not have updated. Let me try to push an update to it to rebuild with the new code.

**Comment by gilbarbara** [comment]
Yeah, I tried in both continuous (stopping in fifth step) and single mode but the beacon didn't show.

**Comment by xveganxxxedgex** [comment]
I still haven't been able to replicate the issue you were seeing, but in efforts to do clean up and more testing to find it, I did notice that my branch has some other bugs. The main one I'm seeing now is the scrollContainer will work fine for the first element, but if you have another targeted element using the same scrollContainer at the step level, it doesn't work right. I'll continue trying to get it right once I have more time, but yeah in the meantime, unfortunately this isn't ready for a PR yet.

**Comment by gilbarbara** [comment]
@xveganxxxedgex Please submit a new PR if you find a way to add this functionality. Thanks

**Comment by martinpesout** [comment]
@xveganxxxedgex Hi I really like this feature and I want to use it in our web app. We are using layout with scrollable areas. So supporting different scrolling containers is need for us. Is there any chance that we will be able to move these changes into @gilbarbara's `react-joyride`?

**Comment by xveganxxxedgex** [comment]
Hello @martinpesout, I resubmitted this PR, but unfortunately it was not an ideal solution and was unable to be merged. You can read more details at the PR here: https://github.com/gilbarbara/react-joyride/pull/174

**Comment by martinpesout** [comment]
Thanks for answer. Is there any plan how to continue now? I can also help and together we can prepare some better solution.

**Comment by xveganxxxedgex** [comment]
Hello @martinpesout, I don't currently have an active plan to proceed. My fork has been working for the purpose we need. I decided it was better to have a less ideal scroller feature than not having any child scrolling at all, as that would make our tour usage seem completely broken. I've been trying to think more of alternate solutions, but haven't had any time to implement or try anything.

**Pull request closed without merging**
