### PR TITLE
Add `fixed` option to position steps as fixed within the viewport

### PR DESCRIPTION
**Pull request by coox**
This is an attempt to solve the position calculation of tooltip+hole/beacon exposed in #71.

I noticed a previous pull request (#112) also partially solving that problem, however it was closed without an explanation, so I hope that this is acceptable. Please let me know if it's not a fit on React-Joyride's roadmap, or if the option should be named otherwise…

### CODE REVIEW

**Comment by chriscain** [comment]
Hey @coox - I actually implemented the same functionality on our fork, and was going to open a PR this weekend - you beat me to it - thanks!

It wouldn't let me comment on the line since it was unchanged, but I believe [this calculation here](https://github.com/gilbarbara/react-joyride/blob/7f96958c56ee1b4b2d279efb9df9c7cffbe825e0/src/scripts/Tooltip.jsx#L134) needs to be conditionally changed based on `fixed` position. If the body is _already_ scrolled, it'll push the overlay hole too far down the page.

Hopefully that makes sense - thanks again!

**Comment by coox** [comment]
Hey @chriscain — You are right, it does make a lot of sense.

Just patched according to your suggestion. At least, I hope this is what you had in mind!

**Comment by chriscain** [comment]
Exactly what I had in mind - thank you! 🎉

**Comment by IanVS** [comment]
Hi @coox.  When naming variables and options, I've often found it helpful to start booleans with `is` or `has`.  So, it might be a little more clear to name this property `isFixedPosition` or something like that.  That's just a suggestion though, I'm not a maintainer on this project, it's up to @gilbarbara.  :)

**Comment by gilbarbara** [comment]
Needs rebasing.

**Comment by coox** [comment]
Hi @IanVS. Thanks for the suggestion, with which I agree.
It didn't seem that the project was enforcing this sort of convention, so I went with a shorter option name… As you say, it's really ultimately up to the maintainer, who can envision the API as a whole. Maybe for version 2.0?

**Pull request merged**
