### PR TITLE
Scroll to fix

### PR DESCRIPTION
**Pull request by Alpa84**

### CODE REVIEW

**Comment by gilbarbara** [comment]
@Alpa84 Did you test these changes with the demo? I think you'll need to update it to include this case.

**Comment by Alpa84** [comment]
@gilbarbara I tested these changes with the demo everything worked fine.
In the process I found a bug when you hit 'next' for the first time on the 'scroll' page. That bug is not related to these changes and also appear when using the unmodified package.
I will create an issue for that one.

**Comment by Alpa84** [comment]
> I will create an issue for that one.
 #594

**Comment by gilbarbara** [comment]
@Alpa84 
I've merged this in the command line but GitHub didn't catch it.

Thanks

**Pull request closed without merging**
