### PR TITLE
Support for horizontal scrolling

### PR DESCRIPTION
**Pull request by xveganxxxedgex**
This PR includes:

* Support for scrollParents to scroll horizontally to step targets
* Support for nested targets (offset values were only relative to the parent, so for some step targets this may not have worked before)
* A doc fix reflecting that `run` is actually true by default
* Pass previous step to callback on step_after and on tour end (it was either passing the next step, or undefined, for these events which felt incorrect to me, but lmk if I'm misunderstanding why that may have been intentional)
* Exposes the reset functionality to `this.joyride` when set in refs
    * If there's an existing/preferred way that should be used instead to reset the tour, let me know and I can remove this. I know it existed in the previous version and I found it very helpful, but it may be considered anti-pattern in this new version that I wasn't aware of.

I added the option to enable horizontal scrolling, but should it just be enabled by default/no need for a special setting?

Let me know if you have any questions or feedback. Thanks for reviewing!

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hello @xveganxxxedgex 

Thanks for the PR!
But it changes too much and the scope should be the horizontal scrolling, nothing else.

As I said before I wasn't looking to add this to avoid bloating and keep maintainability low, so it needs to works super well and be tested thoroughly...
I think you are the only person ever to ask for it.

- I don't think it should have a flag, it should be transparent.
- Make sure all the examples in the demo work properly with your changes. You can download the demo source from codesandbox and npm link your local package.
- Since this is a big change, please create a new functional example that follows the other examples UI and have a real-world usability. You can attach the new example component to a comment.
- make sure all checks are green
---

Nested targets and offset values? What do you mean by this?

I've already updated the docs and I'll commit te change soon.

V2 works differently. If you need to control the state you'll have to use the controlled mode.

**Comment by xveganxxxedgex** [comment]
@gilbarbara 

Thanks for giving it a look and your feedback!

I've removed the unrelated code, though I would be interested in submitting a separate PR for passing the previous step to the end and step:after lifecycle events if those changes seemed okay/sensible. 

I've checked out the codesandbox demo locally and have tested all demos, and they all seem to be working as expected. I've also attached the real-world example you requested below (I couldn't attach .js files to this comment for some reason). It's similar to why I need it in my production app, we have a few complex tables that we want to walk users through so they understand what each column and cell content means.

As for the nested targets/offset thing, I realized my changes actually did not fix it as I thought it would. Though this may be another edge case that isn't really meant to be supported. This demo shows what I mean, on the Scroll tab:

https://codesandbox.io/s/w2qnlp227k

For the third step, it scrolls the targets closest parent, but does not scroll the outer scroll container. This could probably be fixed by looping through all potential scrollable parents, but again, this is probably an edge case and may be more exhaustive than it's worth.

I'm still trying to get the codeclimate checks to succeed, but hopefully I can get those to pass shortly. 

Let me know if you have any questions, and thanks again!

```
import React, { Component } from "react";
import PropTypes from "prop-types";
import Joyride from "react-joyride";
import styled from "styled-components";

const DemoSection = styled.div`
  height: 100vh;
  align-items: center;
  display: flex;
  justify-content: center;
  flex-direction: ${props => props.direction || 'row'};
  background-color: ${props => props.background || '#9f9f9f'};
`;

const Wrapper = styled.div`
  background-color: #ccc;
  height: 100vh;
  width: 100vw;
  overflow: auto;
`;

const TableWrapper = styled.div`
  height: 50vh;
  max-width: 500px;
  overflow: auto;
  background-color: #fff;
`;

const StyledTbody = styled.tbody`
  height: calc(100% - 44px);
`;

const StyledTh = styled.th`
  padding: 10px 20px;
  white-space: nowrap;
`;

const StyledTd = styled.td`
  padding: 10px 20px;
  white-space: nowrap;
`;

class HorizontalScrollDemo extends Component {
  state = {
    continuous: true,
    disableOverlayClicks: true,
    modalIsOpen: false,
    run: true,
    steps: [
      {
        content: 'Child scroll containers will automatically scroll to their targets',
        placement: 'top',
        target: 'table th'
      },
      {
        content: 'This is the name for the produce item',
        placement: 'top',
        target: 'table tr:nth-of-type(1) td:nth-of-type(2)',
        title: 'Name'
      },
      {
        content: 'We need to record the supplier for each produce item, since some suppliers only offer certain items.',
        placement: 'top',
        target: 'table tr:nth-of-type(1) td:nth-of-type(6)',
        title: 'Supplier'
      },
      {
        content: 'Sometimes you need to target a specific child. We can scroll to them too.',
        placement: 'top',
        target: 'table tr:nth-of-type(1) td:nth-of-type(7) .order-schedule',
        title: 'Target Nested Children'
      },
      {
        content: 'This item typically only stays fresh and sellable for this many days.',
        placement: 'top',
        target: 'table tr:nth-of-type(1) td:nth-of-type(8)',
        title: 'Shelf Life'
      },
      {
        content: 'Product loss is part of the course of selling produce, as it spoils fairly quickly.',
        placement: 'top',
        target: 'table tr:nth-of-type(1) td:nth-of-type(9)',
        title: 'Percent lost to spoilage'
      },
      {
        content: 'Be sure to keep an eye on the current stock. If there is an excess, we will have more spoilage waste.',
        placement: 'top',
        target: 'table tr:nth-of-type(11) td:nth-of-type(4)',
        title: 'Current Stock'
      }
    ]
  };

  static propTypes = {
    joyride: PropTypes.shape({
      callback: PropTypes.func
    })
  };

  static defaultProps = {
    joyride: {}
  };

  componentDidUpdate(prevProps, prevState) {
    if (!prevState.modalIsOpen && this.state.modalIsOpen) {
      this.start();
    }
  }

  start = () => {
    this.setState({
      run: true,
      stepIndex: 0
    });
  };

  handleJoyrideCallback = data => {
    const { joyride } = this.props;
    const { type } = data;

    if (typeof joyride.callback === "function") {
      joyride.callback(data);
    } else {
      console.group(type);
      console.log(data); //eslint-disable-line no-console
      console.groupEnd();
    }
  };

  renderContent() {
    const inventory = [
      { id: 1, name: 'Blueberries', price: 1.99, stock: 55, uom: 'carton', supplier: 'Berry World', orderSchedule: 1, orderAmount: 30, shelfLife: 3, avgWaste: .22 },
      { id: 2, name: 'Strawberries', price: 2.50, stock: 84, uom: 'carton', supplier: 'Berry World', orderSchedule: 1, orderAmount: 30, shelfLife: 3, avgWaste: .19 },
      { id: 3, name: 'Blackberries', price: 2.99, stock: 23, uom: 'carton', supplier: 'Berry World', orderSchedule: 1, orderAmount: 30, shelfLife: 3, avgWaste: .26 },
      { id: 4, name: 'Raspberries', price: 2.99, stock: 60, uom: 'carton', supplier: 'Berry World', orderSchedule: 1, orderAmount: 30, shelfLife: 3, avgWaste: .27 },
      { id: 5, name: 'Peach', price: 0.50, stock: 39, uom: 'each', supplier: 'Farm Fresh', orderSchedule: 4, orderAmount: 35, shelfLife: 4, avgWaste: .10 },
      { id: 6, name: 'Apple', price: 0.64, stock: 72, uom: 'each', supplier: 'Farm Fresh', orderSchedule: 4, orderAmount: 35, shelfLife: 6, avgWaste: .06 },
      { id: 7, name: 'Bananas', price: 0.49, stock: 46, uom: 'bunch', supplier: 'Farm Fresh', orderSchedule: 5, orderAmount: 40, shelfLife: 5, avgWaste: .05 },
      { id: 8, name: 'Mango', price: 0.98, stock: 22, uom: 'each', supplier: 'Tropic Dream', orderSchedule: 3, orderAmount: 25, shelfLife: 3, avgWaste: .34 },
      { id: 9, name: 'Kiwi', price: 0.30, stock: 35, uom: 'each', supplier: 'Tropic Dream', orderSchedule: 3, orderAmount: 30, shelfLife: 3, avgWaste: .29 },
      { id: 10, name: 'Lemon', price: 0.20, stock: 30, uom: 'each', supplier: 'Jones Citrus', orderSchedule: 3, orderAmount: 40, shelfLife: 6, avgWaste: .08 },
      { id: 11, name: 'Lime', price: 0.15, stock: 25, uom: 'each', supplier: 'Jones Citrus', orderSchedule: 3, orderAmount: 35, shelfLife: 6, avgWaste: .09 },
      { id: 12, name: 'Orange', price: 0.30, stock: 39, uom: 'each', supplier: 'Jones Citrus', orderSchedule: 3, orderAmount: 35, shelfLife: 6, avgWaste: .06 },
      { id: 13, name: 'Grapefruit', price: 0.40, stock: 24, uom: 'each', supplier: 'Jones Citrus', orderSchedule: 3, orderAmount: 25, shelfLife: 5, avgWaste: .12 },
      { id: 14, name: 'Tangerine', price: 0.10, stock: 11, uom: 'each', supplier: 'Jones Citrus', orderSchedule: 3, orderAmount: 20, shelfLife: 3, avgWaste: .17 },
      { id: 15, name: 'Red Grapes', price: 1.99, stock: 52, uom: 'bunch', supplier: 'The Grape People', orderSchedule: 2, orderAmount: 40, shelfLife: 3, avgWaste: .14 },
      { id: 16, name: 'Green Grapes', price: 2.19, stock: 43, uom: 'bunch', supplier: 'The Grape People', orderSchedule: 2, orderAmount: 40, shelfLife: 3, avgWaste: .12 },
      { id: 17, name: 'Watermelon', price: 4.00, stock: 6, uom: 'each', supplier: 'Melons Melons', orderSchedule: 5, orderAmount: 30, shelfLife: 5, avgWaste: .16 },
      { id: 18, name: 'Cantelope', price: 2.00, stock: 12, uom: 'each', supplier: 'Melons Melons', orderSchedule: 5, orderAmount: 22, shelfLife: 4, avgWaste: .18 },
      { id: 19, name: 'Honeydew', price: 2.40, stock: 19, uom: 'each', supplier: 'Melons Melons', orderSchedule: 5, orderAmount: 16, shelfLife: 4, avgWaste: .19 }
    ];

    return (
      <TableWrapper>
        <table>
          <thead>
            <tr>
              <StyledTh>ID</StyledTh>
              <StyledTh>Name</StyledTh>
              <StyledTh>Price</StyledTh>
              <StyledTh>Stock</StyledTh>
              <StyledTh>Unit of Measure</StyledTh>
              <StyledTh>Supplier</StyledTh>
              <StyledTh>Order Schedule</StyledTh>
              <StyledTh>Shelf Life</StyledTh>
              <StyledTh>Avg. Waste Loss</StyledTh>
            </tr>
          </thead>
          <StyledTbody>
            {inventory.map(item => (
              <tr>
                <StyledTd>{item.id}</StyledTd>
                <StyledTd>{item.name}</StyledTd>
                <StyledTd>${item.price.toFixed(2)}</StyledTd>
                <StyledTd>{item.stock}</StyledTd>
                <StyledTd>{item.uom}</StyledTd>
                <StyledTd>{item.supplier}</StyledTd>
                <StyledTd>
                  <span className="order-amount">{item.orderAmount} every </span>
                  <span className="order-schedule">{item.orderSchedule} day(s)</span>
                </StyledTd>
                <StyledTd>{item.shelfLife}</StyledTd>
                <StyledTd>{(item.avgWaste * 100).toFixed(0)}%</StyledTd>
              </tr>
            ))}
          </StyledTbody>
        </table>
      </TableWrapper>
    );
  }

  render() {
    const joyrideProps = {
      ...this.state,
      ...this.props.joyride
    };

    return (
      <Wrapper>
        <Joyride
          scrollToFirstStep
          showSkipButton
          {...joyrideProps}
          callback={this.handleJoyrideCallback}
        />
        <DemoSection direction="column">
          <h1>Inventory</h1>
          {this.renderContent()}
        </DemoSection>
      </Wrapper>
    );
  }
}

export default HorizontalScrollDemo;
```

**Comment by MoritzStefaner** [comment]
Did you have any luck with getting this to run? I'd like to use react-joyride on a horizontally scrolling page as well…

**Comment by maureenwaggl** [comment]
@MoritzStefaner I had it working for what I needed in my forked repo, but I think it's pretty outdated at this point

**Comment by xveganxxxedgex** [comment]
@MoritzStefaner I had it working for what I needed in my forked repo, but I think it's pretty outdated at this point

**Comment by gilbarbara** [comment]
Thanks for your work here but since it doesn't appeal for a lot of users, I'm closing it.
🙏🏻

**Pull request closed without merging**
