### PR TITLE
Fix disableScrolling prop in the step not overriding the global value

### PR DESCRIPTION
**Pull request by delewis13**
Fix something missed in https://github.com/gilbarbara/react-joyride/pull/736 

It would be good if the `shouldScroll` prop of `<Step />` also used this `shouldScroll` method, but wanted to make minimal changes to get things working

### CODE REVIEW

**Comment by gilbarbara** [comment]
hey @delewis13 

You are trying to merge my own commit back to master?

**Comment by delewis13** [comment]
LOL 🤣 

I have evidently made some mistake here, not exactly sure what's gone on, but am about to head to bed will take a look TMR - sorry 😅

**Comment by delewis13** [comment]
Errr I don't know what's gone on, or why you are listed author of 22776b7. I must have done something odd in git, but the PR diff matches up with what I would expect (just fixing the arg input to `this.shouldScroll`). 

I have my own fork of the repo with a branch called `gilbarbara:master`. I added the fix there, then pulled from upstream [your master], then submitted this PR.

**Comment by gilbarbara** [comment]
Too messy

**Pull request closed without merging**
