### PR TITLE
Fixed problem with modals and positioning.

### PR DESCRIPTION
**Pull request by ddeath**
This is remake of #214 on the actual master. It uses code from this SO answer which has 220 upvotes:
[http://stackoverflow.com/questions/442404/retrieve-the-position-x-y-of-an-html-element#answer-442474](http://stackoverflow.com/questions/442404/retrieve-the-position-x-y-of-an-html-element#answer-442474)

This should fix problems with positioning in different scenarios. With this fix the react-joyride is working properly in our app.

I also added modal example to the demo code which demonstrates one situation which gets fixed with this PR.

On master the beacon is in the middle of the text even when position is set to bottom:
bug_master_beacon

On master the tooltip is positioned wrong:
but_master_tooltip

With this fix beacon is positioned on the bottom:
bug_fix_beacon

With this fix tooltip is positioned correctly:
bug_fix_tooltip

### CODE REVIEW

**Comment by freefire8** [comment]
Any news on that fix? :)

**Comment by ddeath** [comment]
Not really. I am using my own fork now.

**Comment by ojame** [comment]
Is there any reason why this hasn't been merged? It fixes a critical issue.

**Comment by gilbarbara** [comment]
This will be handled differently in V2.
Thanks for the PR

**Pull request closed without merging**
