### PR TITLE
fix: check of null elements of query selector during unmount

### PR DESCRIPTION
**Pull request by mujuni88**
This PR should fix an issue below that I was getting when I exited Joyride to view another component
```
Uncaught TypeError: Cannot read property 'removeEventListener' of null
    at eval (eval at <anonymous> (http://localhost:8888/assets/app.js:8621:2), <anonymous>:12:575)
    at Array.forEach (native)
    at Joyride.componentWillUnmount (eval at <anonymous> (http://localhost:8888/assets/app.js:8621:2), <anonymous>:12:526)
```

### CODE REVIEW

**Comment by gilbarbara** [comment]
@IanVS did you test this?

**Comment by IanVS** [comment]
No, I am not so familiar with this part of the code, and I've never had this problem before.

@mujuni88, perhaps you can give us some instructions for how to recreate the problem you were having, so that we can test out this change?

**Comment by mujuni88** [comment]
I'll create a sample project soon but meanwhile, you can create 3 components.

**Comment by mujuni88** [comment]
I'm able to replicate the issue [Demo](https://build-bjekjesdbk.now.sh/). When you switch from ComponentJ (with Joyride) and ComponentK, you will see the following error:

**Comment by IanVS** [comment]
Thanks @mujuni88.  Is there any chance you can share the source to the demos you created?  Those are very helpful, but it would be great to also see the code to make sure I understand exactly what's going on.  If not, it's no big deal.

Thanks again!

**Comment by mujuni88** [comment]
The source code for the demo can be found [here](https://github.com/mujuni88/joyride-test). I created two branches: `master` and `solution`. 

The difference: 
- `master` depends `"react-joyride": "^1.9.0"` 
- `solution` branch depends on my fork with the fix: 
```{"react-joyride": "git+ssh://git@github.com/mujuni88/react-joyride.git#dev"}```

**Comment by IanVS** [comment]
Thanks @mujuni88.  I guess the core cause of the problem is that the DOM elements are destroyed before `componentWillUnmount` has a chance to remove the listeners, right?  In any case, the changes look good and ultimately solve your problem.  Thanks for contributing!

**Pull request merged**
