### PR TITLE
Handle unmounted steps

### PR DESCRIPTION
**Pull request by IanVS**
## Description

This PR builds off the work done by @goloveychuk in https://github.com/gilbarbara/react-joyride/pull/167.  

This PR changes the behavior of `react-joyride` when it tries to render a tooltip or beacon for a step's selector which it cannot find in the DOM.  Rather than simply incrementing/decrementing the index to skip the step, a callback is now triggered and the joyride is stopped.  This way, it allows the application to decide what to do when a target element is not found.

An app can still accomplish the same behavior by listening to the callback and incrementing/decrementing the `stepIndex` prop as appropriate.  The demo has been updated to demonstrate exactly this.

The app could also stop the joyride and then retry after a period of time, in case it is waiting for an element to be added to its DOM.

## To Test

Click through the demo as usual, and verify that apart from seeing a console warning about a missing target, everything works as normal.

## Reviewers Should Focus On

I'm slightly nervous about the change to `componentWillReceiveProps`, because the added `if` statement is not comparing current to next props, but rather next props to current state.  I think this is good to do in this case, because if an app keeps the `run` prop turned on, and the Joyride itself stops running because it could not find a target, it's nice for the app to be able to just change the stepIndex and allow the joyride to keep going.  Without that change to `componentWillReceiveProps`, the application would have to use two render cycles -- the first to turn `run` to false, and a second to change the index and turn `run` back to true.

I think it is safe, because if the app is changing the `stepIndex` and `run` is true, I think the app should have a reasonable expectation that the joyride will run at the specified `stepIndex`.  I just wanted to call this out for review.

### CODE REVIEW

**Comment by IanVS** [comment]
I tested this out in my own application, and it works well after I added the last commit (2f4b384).  I realized it was necessary because in some cases in my application, I stop the joyride, change the index, and then restart it.  This will also handle an unmounted target on the first step as well.

**Comment by goloveychuk** [comment]
@IanVS you have proper step on `error:target_not_found` cb?

**Comment by IanVS** [comment]
Great find, @goloveychuk!  I've corrected it now.

**Comment by goloveychuk** [comment]
lgtm!

**Comment by IanVS** [comment]
Actually, I may need to also make changes to the `start()` method.  I'll look a bit deeper tonight.  Don't merge for now.

**Comment by IanVS** [comment]
OK, I've done a bit more cleanup, as I've tried to document in the commit messages.  

To test that everything works correctly in the test demo, turn on `debug`, and change the selector of the first step so that it cannot be found.  The joyride will jump straight to the second step when you start it.  If you click `back` on that step, the joyride will `finish`, but that's just because the error callback handler is not smart enough to deal with it, and sends the joyride back to step `-1`.

I believe this is ready for your final review, @gilbarbara.

**Comment by gilbarbara** [comment]
So maybe this "second" step shouldn't display a Back button since it is actually the first one?

**Comment by IanVS** [comment]
>So maybe this "second" step shouldn't display a Back button since it is actually the first one?

Even if we wanted to, I'm not sure how we would manage that.  We would somehow have to keep track of steps which had targets which were not found.  I think it's probably _such_ an edge case (this is an error condition, after all), that it's probably not worth adding extra complexity.  If someone really has a compelling case for it, maybe we can consider it.  But until then, I'm just not sure it's worth it.

Or maybe you have some easy way in mind to implement it?  If so, and you're happy with the rest of this PR, maybe we can tackle that as a subsequent effort?

Note: it might be good to release a patch version of `react-joyride` with the current bugfixes before we merge this PR, as I think this one will probably need a minor bump.  What do you think?

**Pull request merged**
