### PR TITLE
feat: Add support for react 19 and remove support for react <16.3

### PR DESCRIPTION
**Pull request by drosi94**
Hello, as react 19 is about to be released soon, I made it some updates to remove the deprecated code from react-dom to support react 19.

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hey @drosi94 
Removing support for React 15 would require a major version release, and I don't see the point right now.
Thanks for the PR, but I had other tasks before releasing a major version.

**Comment by dillonrowan** [comment]
Is there a timeline when this project will support react 19? My team and I were considering adopting joyride, but will probably look for another UI tour solution due to the lack of support.

**Comment by drosi94** [comment]
Use driver.js for react 19, it works fine!

**Comment by gilbarbara** [comment]
@dillonrowan 
You can use the next version.
`npm i react-joyride@next`

**Comment by dillonrowan** [comment]
@gilbarbara Thank you for sharing. Could you please share any documentation on react-joyride@next?

**Comment by gilbarbara** [comment]
Hey @dillonrowan 
It's the same documentation as v2, just some internal changes and dropped support for react < 16.8

**Pull request closed without merging**
